### ISSUE TITLE
Add Firebase Cloud Messaging (FCM) check

### ISSUE THREAD

**Issue by HiddeSmit** [ozguralp/gmapsapiscanner#10]
You can check if an API key works for FCM by using the curl below:

```
api_key=YOUR_SERVER_KEY


curl --header "Authorization: key=$api_key" \
     --header Content-Type:"application/json" \
     https://fcm.googleapis.com/fcm/send \
     -d "{\"registration_ids\":[\"ABC\"]}"
```

Source: https://abss.me/posts/fcm-takeover/

Would be cool if this would be integrated in the script. I will be trying to integrate this myself sometime soon, so I might come back later with a pull request.

**Comment by ozguralp** [comment]
A little bit busy lately so not sure when to pull this request. Will be really glad for the contributions as well :) Intergrating this script to all Google API's on my to-do list as well however not sure when I can finish it completely.

**Comment by ozguralp** [comment]
Added on latest update.
