### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by welltest** [ozguralp/gmapsapiscanner#13]
![2021-02-01 23_27_13-VPS](https://user-images.githubusercontent.com/7748482/106498309-34241380-64e5-11eb-9166-f2c41815e28f.png)

**Comment by sawzeeyy** [comment]
Oh! That's only missing a colon. Add colon, **:** at the end of 11. So it looks like the following

```
if response.text.find("errors") < 0:
```

**Comment by ozguralp** [comment]
That's my bad, sorry! Confirmed pull request so it should be ready to go.
