### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by welltest** [ozguralp/gmapsapiscanner#14]
I tried

pip install requests
pip3 install requests

& pip uninstall requests , pip3 uninstall requests and then install bu still facing bellow issue
![2021-02-01 23_29_46-VPS](https://user-images.githubusercontent.com/7748482/106498696-a39a0300-64e5-11eb-93ad-4a14941f498c.png)

**Comment by 0xklaue** [comment]
This is for python2. For python2, you need to try the following: `python2 -m pip install requests`

**Comment by ozguralp** [comment]
Thanks for the recommendation @0xklaue, @welltest  @0xklaue is right, due to you installed different versions of python your script does not see the request module. `python2 -m pip install requests` should help.
