### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by CHERYLMAISELOBO** [ozguralp/gmapsapiscanner#22]
Hello,

I try running the command >python3 maps_api_scanner_python3.py and keeps throwing the same error.  

How can I fix this issue?

![GMAPSAPISCANNER](https://github.com/ozguralp/gmapsapiscanner/assets/46939903/9ca24dff-46ed-4830-9e4c-4a8bcd2f206e)

**Comment by ozguralp** [comment]
Hi,

Did you try to google the error message? :)

**Comment by CHERYLMAISELOBO** [comment]
My bad! Kill me! Where can I hide my face?!

Thanks btw.

**Comment by ozguralp** [comment]
Glad to help :)
