### ISSUE TITLE
add referer 

### ISSUE THREAD

**Issue by niksthehacker** [ozguralp/gmapsapiscanner#3]
https://github.com/streaak/keyhacks/pull/63

**Comment by ozguralp** [comment]
Hey @niksthehacker,

You don't need any referer header for this result actually, whether it has the referer header on it or not, it still verboses the result. My script is also already returning the reason of the rejection as well. 

You can see the example:
![Screen Shot 2020-03-25 at 10 45 57](https://user-images.githubusercontent.com/28699863/77513360-e5016100-6e85-11ea-9ed6-c61f13647441.jpg)
