### ISSUE TITLE
Add Containerfile to repo

### ISSUE THREAD

**Issue by emanuelb** [ozguralp/gmapsapiscanner#9]
Example:

.dockerignore file content:
```
Containerfile
LICENSE
README.md
maps_api_scanner.py
```

Here what I use on latest fedora: (after `git clone --depth 1` this repo)
Build by: `podman build --rm -t gmapsapiscanner .`
Run by: `podman run --name gmapsapiscanner -ti --entrypoint /bin/sh --rm gmapsapiscanner` then `python3 maps_api_scanner_python3.py` and enter the key.

Containerfile content:
```dockerfile
FROM python:alpine

RUN set -ex; \
   apk update; \
   apk upgrade; \
   adduser -D appuser

USER appuser
WORKDIR /home/appuser/gmapsapiscanner/
COPY . /home/appuser/gmapsapiscanner/

RUN set -ex; \
    pip3 install requests
```

it will be possible to use it from command-line without enter container if api-key can be set by argument, issue #8 , then ContainerFile can have add at the bottom:
```dockerfile
ENTRYPOINT ["python3", "maps_api_scanner_python3.py", "--apikey"]
```
and be run like: 
`podman run --name gmapsapiscanner --rm gmapsapiscanner API_KEY_HERE`

**Comment by ozguralp** [comment]
Well, due to I am not using containers too much & not having too many requests for it from community, I decided to not developing/adding this feature. If you want to contribute, you are more than welcome to make a pull request. Meanwhile, I am closing the issue.
